# config/__init__.py
from .settings import (
    # 기존 설정값들
    SQS_QUEUE_URL,
    SPRING_BOOT_API_ENDPOINT,
    GROQ_API_KEY,
    INGESTION_S3_BUCKET_NAME,
    FAISS_INDEX_S3_BUCKET,
    FAISS_INDEX_S3_PREFIX,
    FAISS_INDEX_FILE_NAME,
    FAISS_METADATA_FILE_NAME,

    # NLP Model & Processing Configurations
    EMBEDDING_MODEL_NAME_OR_PATH,
    EMBEDDING_CHUNK_SIZE_CHARS,
    EMBEDDING_CHUNK_OVERLAP_CHARS,
    EMBEDDING_DIMENSION,

    SUMMARIZER_MODEL_NAME,
    SUMMARIZER_MAX_CHARS_SINGLE_API_CALL,
    SUMMARIZER_CHUNK_TARGET_SIZE_CHARS,
    SUMMARIZER_CHUNK_OVERLAP_CHARS,
    SUMMARIZER_MAX_TOKENS_CHUNK_SUMMARY,
    SUMMARIZER_MIN_TEXT_LENGTH_LONG_SUMMARY_CHARS,
    SUMMARIZER_LONG_SUMMARY_TARGET_CHARS,
    SUMMARIZER_LONG_SUMMARY_MAX_TOKENS,
    SUMMARIZER_SHORT_SUMMARY_MAX_TOKENS,

    TAG_EXTRACTOR_NUM_TAGS,

    CATEGORIZER_SIMILARITY_THRESHOLD,
    CATEGORIES_FILE_PATH, # 새로 추가된 설정

    # Worker Settings
    FAISS_SAVE_INTERVAL_MESSAGES,

    # Testing Configurations
    MOCK_S3,
    TMP_DIR,
    PROJECT_ROOT_DIR, # 필요하다면 프로젝트 루트 경로도 export
)
