# config/__init__.py
from .settings import (
    SQS_QUEUE_URL,
    SPRING_BOOT_API_ENDPOINT,
    GROQ_API_KEY,
    FAISS_INDEX_S3_BUCKET,
    FAISS_INDEX_S3_PREFIX,
    FAISS_INDEX_FILE_NAME,
    FAISS_METADATA_FILE_NAME,
    INGESTION_S3_BUCKET_NAME,
    LOG_LEVEL
)